name: Build and deploy Docker images to AWS ECR (Elastic Container Registry)

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    ECR_REGISTRY: ${{ secrets.ECR_ARTIFACT_REGISTRY }}
    IMAGE_TAG: ${{ github.sha }}
    IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
    build_deploy:
        runs-on: ubuntu-latest

        steps:
            - 
                name: Check out code
                uses: actions/checkout@v3

            - 
                name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: 'maven'

            -
                name: Update Maven snapshots
                run: mvn -U dependency:resolve

            -
                name: Configure AWS credentials via OIDC
                uses: aws-actions/configure-aws-credentials@v4
                with:
                  role-to-assume: arn:aws:iam::529236942244:role/github-actions-ecr
                  aws-region: eu-central-1

            -
                name: Login to Amazon ECR
                uses: aws-actions/amazon-ecr-login@v2

            - 
                name: Build, tag, and push backend Docker image to AWS ECR
                run: |
                    docker build \
                      -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
                      -t $ECR_REGISTRY/$IMAGE_NAME:latest \
                      -f ./Dockerfile .

                    docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
                    docker push $ECR_REGISTRY/$IMAGE_NAME:latest